"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$username\
$hostname\
${env_var.ZMX_SESSION}\
$all\
"""

[character]
success_symbol = '[\$](green)'
error_symbol = '[\$](green)'

[username]
format = '[$user]($style) '

[hostname]
ssh_symbol = " "
format = 'at [$ssh_symbol$hostname]($style) '

[directory]
truncation_length = 2
read_only = " 󰌾"

[git_branch]
symbol = " "

[git_commit]
tag_symbol = '  '

[nodejs]
symbol = " "

[python]
symbol = " "

[docker_context]
symbol = " "

[package]
disabled = true

[cmd_duration]
disabled = true

[battery]
disabled = true

[aws]
disabled = true

[kubernetes]
disabled = true

[env_var.ZMX_SESSION]
symbol = "󰧾 "
format = "[$symbol$env_value]($style) "
description = "zmx session name"
style = "bold green"
