
export SPACESHIP_CHAR_SYMBOL='$'
export SPACESHIP_CHAR_SUFFIX=' '

export SPACESHIP_PACKAGE_SHOW=false
export SPACESHIP_EXEC_TIME_SHOW=false
export SPACESHIP_AWS_SHOW=false
export SPACESHIP_BATTERY_SHOW=false
export SPACESHIP_VI_MODE_SHOW=false
export SPACESHIP_EMBER_SHOW=false
export SPACESHIP_KUBECTL_CONTEXT_SHOW=false

export SPACESHIP_DIR_TRUNC=2
